"""Hermes iOS phone plugin registration."""
from . import schemas, tools


def register(ctx):
    ctx.register_tool(
        name="ios_phone_begin_upload",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_BEGIN_UPLOAD,
        handler=tools.ios_phone_begin_upload,
    )
    ctx.register_tool(
        name="ios_phone_link",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_LINK,
        handler=tools.ios_phone_link,
    )
    ctx.register_tool(
        name="ios_phone_wait_for_files",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_WAIT_FOR_FILES,
        handler=tools.ios_phone_wait_for_files,
    )
    ctx.register_tool(
        name="ios_phone_read_latest_file",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_READ_LATEST_FILE,
        handler=tools.ios_phone_read_latest_file,
    )
    ctx.register_tool(
        name="ios_phone_status",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_STATUS,
        handler=tools.ios_phone_status,
    )
    ctx.register_tool(
        name="ios_phone_list_files",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_LIST_FILES,
        handler=tools.ios_phone_list_files,
    )
    ctx.register_tool(
        name="ios_phone_read_file",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_READ_FILE,
        handler=tools.ios_phone_read_file,
    )
    ctx.register_tool(
        name="ios_phone_summary",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_SUMMARY,
        handler=tools.ios_phone_summary,
    )
    ctx.register_tool(
        name="ios_phone_create_zip",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_CREATE_ZIP,
        handler=tools.ios_phone_create_zip,
    )
    ctx.register_tool(
        name="ios_phone_send_text",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_SEND_TEXT,
        handler=tools.ios_phone_send_text,
    )
    ctx.register_tool(
        name="ios_phone_delete_file",
        toolset="ios_phone",
        schema=schemas.IOS_PHONE_DELETE_FILE,
        handler=tools.ios_phone_delete_file,
    )
