"""Hermes phone plugin registration."""
from . import schemas, tools


def register(ctx):
    ctx.register_tool(
        name="phone_begin_upload",
        toolset="phone",
        schema=schemas.PHONE_BEGIN_UPLOAD,
        handler=tools.phone_begin_upload,
    )
    ctx.register_tool(
        name="phone_link",
        toolset="phone",
        schema=schemas.PHONE_LINK,
        handler=tools.phone_link,
    )
    ctx.register_tool(
        name="phone_wait_for_files",
        toolset="phone",
        schema=schemas.PHONE_WAIT_FOR_FILES,
        handler=tools.phone_wait_for_files,
    )
    ctx.register_tool(
        name="phone_read_latest_file",
        toolset="phone",
        schema=schemas.PHONE_READ_LATEST_FILE,
        handler=tools.phone_read_latest_file,
    )
    ctx.register_tool(
        name="phone_status",
        toolset="phone",
        schema=schemas.PHONE_STATUS,
        handler=tools.phone_status,
    )
    ctx.register_tool(
        name="phone_list_files",
        toolset="phone",
        schema=schemas.PHONE_LIST_FILES,
        handler=tools.phone_list_files,
    )
    ctx.register_tool(
        name="phone_read_file",
        toolset="phone",
        schema=schemas.PHONE_READ_FILE,
        handler=tools.phone_read_file,
    )
    ctx.register_tool(
        name="phone_summary",
        toolset="phone",
        schema=schemas.PHONE_SUMMARY,
        handler=tools.phone_summary,
    )
    ctx.register_tool(
        name="phone_create_zip",
        toolset="phone",
        schema=schemas.PHONE_CREATE_ZIP,
        handler=tools.phone_create_zip,
    )
    ctx.register_tool(
        name="phone_send_text",
        toolset="phone",
        schema=schemas.PHONE_SEND_TEXT,
        handler=tools.phone_send_text,
    )
    ctx.register_tool(
        name="phone_delete_file",
        toolset="phone",
        schema=schemas.PHONE_DELETE_FILE,
        handler=tools.phone_delete_file,
    )
